# Generated by Django 4.2.5 on 2023-09-08 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.customuser')),
            ],
        ),
    ]
