# Generated by Django 4.2.5 on 2023-09-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='Profile_picture',
            field=models.ImageField(blank=True, default='static/profile-images/PROFILE.png', null=True, upload_to='static/profile-images'),
        ),
    ]
