# Generated by Django 4.2.5 on 2023-09-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_customuser_age_remove_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/profile-images/PROFILE.png', null=True, upload_to='static/profile-images'),
        ),
    ]
