# Generated by Django 4.2.5 on 2023-10-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/profile-images/PROFILE.png', null=True, upload_to='static/profile-images'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
