# Generated by Django 4.2.5 on 2023-10-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_customuser_profile_picture_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/PROFILE.png', null=True, upload_to='static/profile-images'),
        ),
    ]
