# Generated by Django 4.2.5 on 2023-09-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherinfo',
            old_name='city',
            new_name='city_name',
        ),
    ]
