# Generated by Django 4.2.5 on 2023-09-10 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_profile_picture_profile_user_and_more'),
        ('weather_app', '0002_rename_city_weatherinfo_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.customuser'),
        ),
    ]
