# Generated by Django 4.2.5 on 2023-09-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0004_alter_weatherinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherinfo',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
