# Generated by Django 4.2.5 on 2023-09-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_remove_flashcard_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='is_pinned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
