# Generated by Django 4.2.5 on 2023-09-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_flashcard_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
