# Generated by Django 4.2.5 on 2023-09-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0006_alter_flashcard_user_alter_flashcardcategory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='flashcardcategory',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
