# Generated by Django 4.2.5 on 2023-09-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-is_pinned', 'name']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-is_pinned', '-is_complete', 'title']},
        ),
        migrations.AddField(
            model_name='task',
            name='is_pinned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
