# Generated by Django 4.2.5 on 2023-09-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_alter_category_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-is_pinned', 'category_name']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='colour',
            new_name='category_colour',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
