# Generated by Django 4.2.5 on 2023-09-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_alter_task_options_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_colour',
            field=models.CharField(blank=True, choices=[('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('grey', 'Grey')], default='white', max_length=6, null=True),
        ),
    ]
