# Generated by Django 4.2.5 on 2023-09-20 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_profile_profile_picture'),
        ('to_do_list', '0005_alter_category_category_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.customuser'),
        ),
    ]
