# Generated by Django 4.2.5 on 2023-09-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0006_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
