# Generated by Django 4.2.5 on 2023-09-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0007_alter_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
