# Generated by Django 4.2.5 on 2023-10-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0008_category_slug_task_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
